export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const FETCH_RECLAMATIONS_REQUEST = 'FETCH_RECLAMATIONS_REQUEST';
export const FETCH_RECLAMATIONS_SUCCESS = 'FETCH_RECLAMATIONS_SUCCESS';
export const FETCH_RECLAMATIONS_FAILURE = 'FETCH_RECLAMATIONS_FAILURE';

// --- NOUVEAU : Pour charger une seule réclamation ---
export const FETCH_RECLAMATION_DETAILS_REQUEST = 'FETCH_RECLAMATION_DETAILS_REQUEST';
export const FETCH_RECLAMATION_DETAILS_SUCCESS = 'FETCH_RECLAMATION_DETAILS_SUCCESS';
export const FETCH_RECLAMATION_DETAILS_FAILURE = 'FETCH_RECLAMATION_DETAILS_FAILURE';
// ----------------------------------------------------

export const CREATE_RECLAMATION_REQUEST = 'CREATE_RECLAMATION_REQUEST';
export const CREATE_RECLAMATION_SUCCESS = 'CREATE_RECLAMATION_SUCCESS';
export const CREATE_RECLAMATION_FAILURE = 'CREATE_RECLAMATION_FAILURE';

export const UPDATE_STATUT_REQUEST = 'UPDATE_STATUT_REQUEST';
export const UPDATE_STATUT_SUCCESS = 'UPDATE_STATUT_SUCCESS';
export const UPDATE_STATUT_FAILURE = 'UPDATE_STATUT_FAILURE';